#!/usr/bin/env bash
# Simple xrandr
#
# A dirty script to manage my notebook's screen output using xrandr.
# srandr is released under WTFPL (DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE).
#
# original script by PkmX
# modified by xatier

lvds=$(xrandr --query | grep " connected" | egrep -om1  '^LVDS[0-9]')
vga=$(xrandr --query  | grep " connected" | egrep -om1 '^VGA[0-9]')
hdmi=$(xrandr --query | grep " connected" | egrep -om1 '^HDMI[0-9]')

eecho()
{
    echo $@ 2>&1
}

# for my laptop
if [[ -n $lvds && -n $vga ]]; then
    [[ -n $2 ]] && mode1="--mode $2" || mode1='--auto'
    [[ -n $3 ]] && mode2="--mode $3" || mode2='--auto'

    case $1 in
        lvds|l)
            xrandr --output "$lvds" $mode1 --output "$vga" --off
            ;;
        vga|v)
            xrandr --output "$lvds" --off  --output "$vga" $mode1
            ;;
        lvds-vga|lv)
            xrandr --output "$lvds" $mode1 --output "$vga" $mode2 --right-of "$lvds"
            ;;
        vga-lvds|vl)
            xrandr --output "$lvds" $mode1 --output "$vga" $mode2 --left-of "$lvds"
            ;;
        mirror|m)
            xrandr --output "$lvds" $mode1 --output "$vga" $mode1 --same-as "$lvds"
            ;;
        debug|d)
            eecho "LVDS: $lvds"
            eecho "VGA: $vga"
            eecho "VGA: $hdmi"
            ;;
        query|q|?)
            xrandr --query
            ;;
        *)
            eecho "Usage: $(basename $0) [lvds|vga|lvds-vga|vga-lvds|mirror|debug|query]"
            eecho "or simple like this => [l|v|lv|vl|m|q]"
            ;;
    esac

else
    # for my desptop
    xrandr --output "HDMI1" --auto --output "HDMI3" --auto --right-of "HDMI1"

    eecho "LVDS: $lvds"
    eecho "VGA: $vga"
    eecho "HDMI: $hdmi"
fi
