name: Test pip

on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    name: Test pip requirements.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Build
        run: |
          python --version
          python -m venv venv
          source venv/bin/activate
          pip install -U pip
          pip install -r pip/requirements.txt

      - name: Show versions
        run: |
          source venv/bin/activate
          set -x
          python --version
          flake8 --version
          yapf --version
          black --version
          pylint --version
          vint --version
          wormhole --version
          set +x
